[opener]
play = [{ run = 'elisa "$@"', orphan = true, for = "unix" }]
edit = [{ run = 'hx "$@"', block = true, for = "unix" }]
open = [{ run = 'xdg-open "$@"', desc = "Open" }]
[tasks]
image_bound = [10000, 10000]
[mgr]
show_hidden = true
